import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";
import Slidebar from "../components/Slidebar";
import CartContent from "../components/CartContent";
import { useDispatch, useSelector } from "react-redux";

export default function Cart() {
  const { t } = useTranslation();
  const router = useRouter();
  const dispatch = useDispatch();
  const cart_products = useSelector((state) => state.cart.products);

  return (
    <div>
      <Head>
        <title>Market Place-Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Slidebar />
        <CartContent />
      </main>
    </div>
  );
}
