import Head from "next/head";
import { useEffect } from "react";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";
import Sliderhome from "../components/Sliderhome";
import Slidebar from "../components/Slidebar";
import ProductsList from "../components/ProductsList";
import ProductLoading from "../components/ProductLoading";
import { productsAsync } from "../features/products/productSlice";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const { t } = useTranslation("common");
  const router = useRouter();
  const dispatch = useDispatch();
  const products = useSelector((state) => state.product.products);
  const loading = useSelector((state) => state.product.loading);

  useEffect(() => {
    dispatch(productsAsync());
  }, []);

  const ratingChanged = (newRating) => {
    console.log(newRating);
  };
  return (
    <div>
      <Head>
        <title>Market Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Slidebar />
        <Sliderhome />
        {loading == true ? (
          <ProductLoading />
        ) : (
          <ProductsList products={products} />
        )}
      </main>
    </div>
  );
}
